///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Android_VBS
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Android_VBSRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("4f3b557c-86f9-4636-bbb1-abef6ac685f4")]
    public partial class Android_VBSRepository : RepoGenBaseFolder
    {
        static Android_VBSRepository instance = new Android_VBSRepository();
        Android_VBSRepositoryFolders.ComVodafoneViewerAppFolder _comvodafoneviewer;

        /// <summary>
        /// Gets the singleton class instance representing the Android_VBSRepository element repository.
        /// </summary>
        [RepositoryFolder("4f3b557c-86f9-4636-bbb1-abef6ac685f4")]
        public static Android_VBSRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Android_VBSRepository() 
            : base("Android_VBSRepository", "/", null, 0, false, "4f3b557c-86f9-4636-bbb1-abef6ac685f4", ".\\RepositoryImages\\Android_VBSRepository4f3b557c.rximgres")
        {
            _comvodafoneviewer = new Android_VBSRepositoryFolders.ComVodafoneViewerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4f3b557c-86f9-4636-bbb1-abef6ac685f4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ComVodafoneViewer folder.
        /// </summary>
        [RepositoryFolder("fef30ae6-57e3-4172-8f0c-1537885189f9")]
        public virtual Android_VBSRepositoryFolders.ComVodafoneViewerAppFolder ComVodafoneViewer
        {
            get { return _comvodafoneviewer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Android_VBSRepositoryFolders
    {
        /// <summary>
        /// The ComVodafoneViewerAppFolder folder.
        /// </summary>
        [RepositoryFolder("fef30ae6-57e3-4172-8f0c-1537885189f9")]
        public partial class ComVodafoneViewerAppFolder : RepoGenBaseFolder
        {
            Android_VBSRepositoryFolders.ContentFolder _content;
            Android_VBSRepositoryFolders.LoginActivityFolder _loginactivity;
            Android_VBSRepositoryFolders.RelativeFolder _relative;
            Android_VBSRepositoryFolders.FormNoneFolder _formnone;
            RepoItemInfo _comgoogleandroidmaterialtextfieldteInfo;
            RepoItemInfo _button1Info;

            /// <summary>
            /// Creates a new ComVodafoneViewer  folder.
            /// </summary>
            public ComVodafoneViewerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComVodafoneViewer", "/mobileapp[@title='com.vodafone.viewer']", parentFolder, 30000, null, false, "fef30ae6-57e3-4172-8f0c-1537885189f9", "")
            {
                _content = new Android_VBSRepositoryFolders.ContentFolder(this);
                _loginactivity = new Android_VBSRepositoryFolders.LoginActivityFolder(this);
                _relative = new Android_VBSRepositoryFolders.RelativeFolder(this);
                _formnone = new Android_VBSRepositoryFolders.FormNoneFolder(this);
                _comgoogleandroidmaterialtextfieldteInfo = new RepoItemInfo(this, "ComGoogleAndroidMaterialTextfieldTe", "form[@title='Enter the password']/container[@rid='content']/androidelement/container[3]/container[@rid='custom']/androidelement/androidelement[2]/container[@containertype='Frame']/text", 30000, null, "1336cd79-cc72-4863-8106-3ba5960fb4a5");
                _button1Info = new RepoItemInfo(this, "Button1", "form[@title='Enter the password']/container[@rid='content']//button[@rid='button1']", 30000, null, "100c61c8-8619-4d29-9345-aaa3cc5a4a41");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fef30ae6-57e3-4172-8f0c-1537885189f9")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fef30ae6-57e3-4172-8f0c-1537885189f9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ComGoogleAndroidMaterialTextfieldTe item.
            /// </summary>
            [RepositoryItem("1336cd79-cc72-4863-8106-3ba5960fb4a5")]
            public virtual Ranorex.Text ComGoogleAndroidMaterialTextfieldTe
            {
                get
                {
                    return _comgoogleandroidmaterialtextfieldteInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ComGoogleAndroidMaterialTextfieldTe item info.
            /// </summary>
            [RepositoryItemInfo("1336cd79-cc72-4863-8106-3ba5960fb4a5")]
            public virtual RepoItemInfo ComGoogleAndroidMaterialTextfieldTeInfo
            {
                get
                {
                    return _comgoogleandroidmaterialtextfieldteInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("100c61c8-8619-4d29-9345-aaa3cc5a4a41")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("100c61c8-8619-4d29-9345-aaa3cc5a4a41")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The Content folder.
            /// </summary>
            [RepositoryFolder("2b51e02a-8b4a-4547-9e5d-f31615d77167")]
            public virtual Android_VBSRepositoryFolders.ContentFolder Content
            {
                get { return _content; }
            }

            /// <summary>
            /// The LoginActivity folder.
            /// </summary>
            [RepositoryFolder("88e6d71e-410d-4537-be77-d8930cf4caf0")]
            public virtual Android_VBSRepositoryFolders.LoginActivityFolder LoginActivity
            {
                get { return _loginactivity; }
            }

            /// <summary>
            /// The Relative folder.
            /// </summary>
            [RepositoryFolder("0c3d9a6d-7cc2-4829-92de-9fdf7ed1c438")]
            public virtual Android_VBSRepositoryFolders.RelativeFolder Relative
            {
                get { return _relative; }
            }

            /// <summary>
            /// The FormNone folder.
            /// </summary>
            [RepositoryFolder("c1608f2e-4491-4de9-b00b-bf8e1b7eae22")]
            public virtual Android_VBSRepositoryFolders.FormNoneFolder FormNone
            {
                get { return _formnone; }
            }
        }

        /// <summary>
        /// The ContentFolder folder.
        /// </summary>
        [RepositoryFolder("2b51e02a-8b4a-4547-9e5d-f31615d77167")]
        public partial class ContentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _nextInfo;

            /// <summary>
            /// Creates a new Content  folder.
            /// </summary>
            public ContentFolder(RepoGenBaseFolder parentFolder) :
                    base("Content", "form[@title>'Enter the username and password']/container[@rid='content']", parentFolder, 30000, null, false, "2b51e02a-8b4a-4547-9e5d-f31615d77167", "")
            {
                _usernameInfo = new RepoItemInfo(this, "Username", "androidelement/container[3]/container[@rid='custom']//text", 30000, null, "dd46132f-f7c2-4367-9753-73c3d9eeb913");
                _passwordInfo = new RepoItemInfo(this, "Password", "androidelement/container[3]/container[@rid='custom']/androidelement/androidelement[2]/container[@containertype='Frame']/text", 30000, null, "915e4c63-8ab0-43ba-9243-e8a0aa300ac5");
                _nextInfo = new RepoItemInfo(this, "Next", ".//button[@rid='button1']", 30000, null, "021fe34e-ecf5-4f11-9b17-0c579dc81138");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2b51e02a-8b4a-4547-9e5d-f31615d77167")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2b51e02a-8b4a-4547-9e5d-f31615d77167")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("dd46132f-f7c2-4367-9753-73c3d9eeb913")]
            public virtual Ranorex.Text Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("dd46132f-f7c2-4367-9753-73c3d9eeb913")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("915e4c63-8ab0-43ba-9243-e8a0aa300ac5")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("915e4c63-8ab0-43ba-9243-e8a0aa300ac5")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Next item.
            /// </summary>
            [RepositoryItem("021fe34e-ecf5-4f11-9b17-0c579dc81138")]
            public virtual Ranorex.Button Next
            {
                get
                {
                    return _nextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Next item info.
            /// </summary>
            [RepositoryItemInfo("021fe34e-ecf5-4f11-9b17-0c579dc81138")]
            public virtual RepoItemInfo NextInfo
            {
                get
                {
                    return _nextInfo;
                }
            }
        }

        /// <summary>
        /// The LoginActivityFolder folder.
        /// </summary>
        [RepositoryFolder("88e6d71e-410d-4537-be77-d8930cf4caf0")]
        public partial class LoginActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _manageInfo;
            RepoItemInfo _editInfo;
            RepoItemInfo _connectInfo;

            /// <summary>
            /// Creates a new LoginActivity  folder.
            /// </summary>
            public LoginActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginActivity", "form[@title='LoginActivity']", parentFolder, 30000, null, false, "88e6d71e-410d-4537-be77-d8930cf4caf0", "")
            {
                _manageInfo = new RepoItemInfo(this, "Manage", ".//container[@containertype='Linear']/?/?/button[@text='manage']", 30000, null, "b9f23425-3ea4-45aa-8656-ffc5cd57f777");
                _editInfo = new RepoItemInfo(this, "Edit", "androidelement[@rid='content']//container[@containertype='Frame']/androidelement/container[@containertype='Relative']/container[@containertype='Relative']/button[@text='Edit']", 30000, null, "41d62841-c2b8-429e-85f1-f132073f4d5c");
                _connectInfo = new RepoItemInfo(this, "Connect", "androidelement[@rid='content']//container[@containertype='Frame']/androidelement/container[@containertype='Relative']/container[@containertype='Relative']/button[@text='Connect']", 30000, null, "411aad86-3124-4e27-996a-721499dd7918");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("88e6d71e-410d-4537-be77-d8930cf4caf0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("88e6d71e-410d-4537-be77-d8930cf4caf0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Manage item.
            /// </summary>
            [RepositoryItem("b9f23425-3ea4-45aa-8656-ffc5cd57f777")]
            public virtual Ranorex.Button Manage
            {
                get
                {
                    return _manageInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Manage item info.
            /// </summary>
            [RepositoryItemInfo("b9f23425-3ea4-45aa-8656-ffc5cd57f777")]
            public virtual RepoItemInfo ManageInfo
            {
                get
                {
                    return _manageInfo;
                }
            }

            /// <summary>
            /// The Edit item.
            /// </summary>
            [RepositoryItem("41d62841-c2b8-429e-85f1-f132073f4d5c")]
            public virtual Ranorex.Button Edit
            {
                get
                {
                    return _editInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Edit item info.
            /// </summary>
            [RepositoryItemInfo("41d62841-c2b8-429e-85f1-f132073f4d5c")]
            public virtual RepoItemInfo EditInfo
            {
                get
                {
                    return _editInfo;
                }
            }

            /// <summary>
            /// The Connect item.
            /// </summary>
            [RepositoryItem("411aad86-3124-4e27-996a-721499dd7918")]
            public virtual Ranorex.Button Connect
            {
                get
                {
                    return _connectInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Connect item info.
            /// </summary>
            [RepositoryItemInfo("411aad86-3124-4e27-996a-721499dd7918")]
            public virtual RepoItemInfo ConnectInfo
            {
                get
                {
                    return _connectInfo;
                }
            }
        }

        /// <summary>
        /// The RelativeFolder folder.
        /// </summary>
        [RepositoryFolder("0c3d9a6d-7cc2-4829-92de-9fdf7ed1c438")]
        public partial class RelativeFolder : RepoGenBaseFolder
        {
            RepoItemInfo _alertsInfo;
            RepoItemInfo _mapsInfo;
            RepoItemInfo _viewoptionsInfo;

            /// <summary>
            /// Creates a new Relative  folder.
            /// </summary>
            public RelativeFolder(RepoGenBaseFolder parentFolder) :
                    base("Relative", "form[@title='HomeScreenActivity']/androidelement[@rid='content']/androidelement/androidelement[1]/androidelement[1]/androidelement[1]/container[@containertype='Relative']", parentFolder, 30000, null, false, "0c3d9a6d-7cc2-4829-92de-9fdf7ed1c438", "")
            {
                _alertsInfo = new RepoItemInfo(this, "Alerts", "androidelement[2]/container[@containertype='Frame']", 30000, null, "13139985-5fbd-4c6a-90f8-92fa7759e618");
                _mapsInfo = new RepoItemInfo(this, "Maps", "container[2]", 30000, null, "448e3749-558e-49c0-93c3-ef3d69435fe1");
                _viewoptionsInfo = new RepoItemInfo(this, "ViewOptions", "picture", 30000, null, "65d50a6c-723d-4cfc-85e6-243726de01d0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0c3d9a6d-7cc2-4829-92de-9fdf7ed1c438")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0c3d9a6d-7cc2-4829-92de-9fdf7ed1c438")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Alerts item.
            /// </summary>
            [RepositoryItem("13139985-5fbd-4c6a-90f8-92fa7759e618")]
            public virtual Ranorex.Container Alerts
            {
                get
                {
                    return _alertsInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Alerts item info.
            /// </summary>
            [RepositoryItemInfo("13139985-5fbd-4c6a-90f8-92fa7759e618")]
            public virtual RepoItemInfo AlertsInfo
            {
                get
                {
                    return _alertsInfo;
                }
            }

            /// <summary>
            /// The Maps item.
            /// </summary>
            [RepositoryItem("448e3749-558e-49c0-93c3-ef3d69435fe1")]
            public virtual Ranorex.Container Maps
            {
                get
                {
                    return _mapsInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Maps item info.
            /// </summary>
            [RepositoryItemInfo("448e3749-558e-49c0-93c3-ef3d69435fe1")]
            public virtual RepoItemInfo MapsInfo
            {
                get
                {
                    return _mapsInfo;
                }
            }

            /// <summary>
            /// The ViewOptions item.
            /// </summary>
            [RepositoryItem("65d50a6c-723d-4cfc-85e6-243726de01d0")]
            public virtual Ranorex.Picture ViewOptions
            {
                get
                {
                    return _viewoptionsInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The ViewOptions item info.
            /// </summary>
            [RepositoryItemInfo("65d50a6c-723d-4cfc-85e6-243726de01d0")]
            public virtual RepoItemInfo ViewOptionsInfo
            {
                get
                {
                    return _viewoptionsInfo;
                }
            }
        }

        /// <summary>
        /// The FormNoneFolder folder.
        /// </summary>
        [RepositoryFolder("c1608f2e-4491-4de9-b00b-bf8e1b7eae22")]
        public partial class FormNoneFolder : RepoGenBaseFolder
        {
            RepoItemInfo _logoutInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _isthefrontendapplicationfromvodafoInfo;

            /// <summary>
            /// Creates a new FormNone  folder.
            /// </summary>
            public FormNoneFolder(RepoGenBaseFolder parentFolder) :
                    base("FormNone", "form[@title='(none)']", parentFolder, 30000, null, false, "c1608f2e-4491-4de9-b00b-bf8e1b7eae22", "")
            {
                _logoutInfo = new RepoItemInfo(this, "Logout", "androidelement/androidelement/androidelement[5]/container[@rid='content']", 30000, null, "ed7e3d58-1034-4aad-aeb2-db8c6093652e");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container[@rid='content']//button[@resourceid='R.string.yes']", 30000, null, "283cd100-5000-445a-b1af-5afab7fe55f7");
                _isthefrontendapplicationfromvodafoInfo = new RepoItemInfo(this, "IsTheFrontEndApplicationFromVodafo", "container[@rid='content']//dom[@containertype='WebView']/body/div/div//article/section/p[@innertext>'is the front end application']", 30000, null, "72d41ec0-df30-4032-b90e-e2f3bc04f9df");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c1608f2e-4491-4de9-b00b-bf8e1b7eae22")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c1608f2e-4491-4de9-b00b-bf8e1b7eae22")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("ed7e3d58-1034-4aad-aeb2-db8c6093652e")]
            public virtual Ranorex.Container Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("ed7e3d58-1034-4aad-aeb2-db8c6093652e")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("283cd100-5000-445a-b1af-5afab7fe55f7")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("283cd100-5000-445a-b1af-5afab7fe55f7")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The IsTheFrontEndApplicationFromVodafo item.
            /// </summary>
            [RepositoryItem("72d41ec0-df30-4032-b90e-e2f3bc04f9df")]
            public virtual Ranorex.PTag IsTheFrontEndApplicationFromVodafo
            {
                get
                {
                    return _isthefrontendapplicationfromvodafoInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The IsTheFrontEndApplicationFromVodafo item info.
            /// </summary>
            [RepositoryItemInfo("72d41ec0-df30-4032-b90e-e2f3bc04f9df")]
            public virtual RepoItemInfo IsTheFrontEndApplicationFromVodafoInfo
            {
                get
                {
                    return _isthefrontendapplicationfromvodafoInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
