///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Android_VBS
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Manage_Edit recording.
    /// </summary>
    [TestModule("45bdbea3-b3a5-403b-8e0f-6f80216d1d64", ModuleType.Recording, 1)]
    public partial class Manage_Edit : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Android_VBSRepository repository.
        /// </summary>
        public static Android_VBSRepository repo = Android_VBSRepository.Instance;

        static Manage_Edit instance = new Manage_Edit();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Manage_Edit()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Manage_Edit Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComVodafoneViewer.LoginActivity.Manage' at Center", repo.ComVodafoneViewer.LoginActivity.ManageInfo, new RecordItemIndex(0));
            repo.ComVodafoneViewer.LoginActivity.Manage.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComVodafoneViewer.LoginActivity.Edit' at Center", repo.ComVodafoneViewer.LoginActivity.EditInfo, new RecordItemIndex(1));
            repo.ComVodafoneViewer.LoginActivity.Edit.Touch();
            Delay.Milliseconds(300);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
